remote_theme: jekyll/minima@0b7ca6bbdb782a646f8e7b78b1a29fd5032ad4d3

plugins:
  - jekyll-remote-theme

minima:
  skin: auto

  hide_site_feed_link: true

  author:
    name: NamelessNanashi
    email: "Nanashi@NamelessNanashi.dev"

  nav_pages:
    - index.md
    - LICENSE.md
